apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-api-job
spec:
  template:
    spec:
      serviceAccountName: k8s-api-job-sa
      containers:
      - name: k8s-api-job
        imagePullPolicy: Always
        image: lmagana92/k8s-api-job:fix
        command: ["python", "/job/job.py"]
      restartPolicy: Never