apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: k8s-api-job-role
rules:
  -
    apiGroups:
      - ""
    resources:
        - pods
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: k8s-api-job-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-api-job-role
subjects:
- kind: ServiceAccount
  name: k8s-api-job-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-api-job-sa